apiVersion: v1
kind: ConfigMap
metadata:
  name: chill-crate-config
  namespace: chill-crate
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_SSL_MODE: "disable"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8081"
  STORAGE_ENDPOINT: http://minio:9000
  STORAGE_REGION: us-west-1