apiVersion: apps/v1
kind: Deployment
metadata:
  name: chill-crate-api
  namespace: chill-crate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chill-crate-api
  template:
    metadata:
      labels:
        app: chill-crate-api
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/mic615/chill-crate-api:dev
          command: ["./migrate"]
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSL_MODE
              value: "disable"
      containers:
        - name: chill-crate-api
          image: ghcr.io/mic615/chill-crate-api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef: { name: chill-crate-config }
            - secretRef:    { name: chill-crate-secret }
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
