apiVersion: v1
kind: Service
metadata:
  name: chill-crate-api-np
  namespace: chill-crate
spec:
  type: NodePort
  selector:
    app: chill-crate-api
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
